#pragma once

#define EE_HANDS
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
//#define MASTER_LEFT
//#define MASTER_RIGHT

//#define QUICK_TAP_TERM 0
//#define TAPPING_TERM 100
